import JSZip from 'jszip';
import Papa from 'papaparse';
import { calculateTaxReport } from './tax-engine';
import { TAX_CONFIG } from './tax-config';

export const generateAuditReport = async () => {
    const report = await calculateTaxReport();
    const zip = new JSZip();

    // 1. Schedule VDA (CSV)
    const csvData = report.details.map(item => ({
        "Date of Transfer": new Date(item.date).toLocaleDateString(),
        "Asset": item.asset,
        "Type": item.type,
        "Cost of Acquisition (INR)": item.costBasis.toFixed(2),
        "Consideration Received (INR)": item.saleValue.toFixed(2),
        "Real Profit/Loss (INR)": item.profit.toFixed(2),
        "Taxable Amount (INR)": item.taxableAmount.toFixed(2),
        "Reasoning": item.reasoning.explanation,
        "Section Reference": item.reasoning.sectionReference
    }));

    const csvString = Papa.unparse(csvData);
    zip.file("Schedule_VDA_Ay_2026-27.csv", csvString);

    // 2. Calculation Log (Text)
    let logContent = `CALCULATION LOG - GENERATED ON ${new Date().toISOString()}\n`;
    logContent += `Fiscal Year: ${TAX_CONFIG.fiscalYear}\n`;
    logContent += `----------------------------------------\n\n`;

    logContent += `TOTAL SUMMARY:\n`;
    logContent += `Total Gains from VDAs: ₹${report.totalGains.toFixed(2)}\n`;
    logContent += `Total Tax (30%):       ₹${report.totalTax.toFixed(2)}\n`;
    logContent += `Health & Edu Cess (4%):₹${report.totalCess.toFixed(2)}\n`;
    logContent += `Total Tax Liability:   ₹${report.finalTaxLiability.toFixed(2)}\n\n`;

    logContent += `DETAILED BREAKDOWN BY TRANSACTION:\n`;
    report.details.forEach((tx, idx) => {
        logContent += `\n[${idx + 1}] Transaction ID: ${tx.txId}\n`;
        logContent += `    Asset: ${tx.asset} | Type: ${tx.type}\n`;
        logContent += `    Sale Value: ₹${tx.saleValue.toFixed(2)} - Cost Basis: ₹${tx.costBasis.toFixed(2)} = PnL: ₹${tx.profit.toFixed(2)}\n`;
        if (tx.profit < 0) {
            logContent += `    NOTE: LOSS IGNORED as per Section 115BBH (No Set-off allowed)\n`;
        }
        logContent += `    Taxable Amount: ₹${tx.taxableAmount.toFixed(2)}\n`;
        logContent += `    Legal Reasoning: ${tx.reasoning.explanation} (${tx.reasoning.sectionReference})\n`;
    });

    zip.file("Calculation_Log.txt", logContent);

    // 3. Reasoning Report (Markdown)
    let mdContent = `# Crypto Tax Compliance Report\n\n`;
    mdContent += `**Generated By**: Private DeFi Tax Platform\n`;
    mdContent += `**Date**: ${new Date().toLocaleDateString()}\n\n`;

    mdContent += `## Methodology\n`;
    mdContent += `This report is generated based on the **FIFO (First-In-First-Out)** accounting method for cost basis determination.\n`;
    mdContent += `Tax liability is calculated strictly in accordance with **Section 115BBH** of the Income Tax Act, 1961 (India).\n\n`;

    mdContent += `### Key Compliance Checks:\n`;
    mdContent += `- **Flat 30% Tax**: Applied on all positive gains.\n`;
    mdContent += `- **No Set-off of Losses**: Losses from one VDA are NOT set off against gains from another.\n`;
    mdContent += `- **No Carry Forward**: Losses are not carried forward to subsequent years.\n`;
    mdContent += `- **Cost of Acquisition**: Only purchase cost is deducted (no expenses/fees allowed except transfer fees if applicable).\n\n`;

    mdContent += `## Disclaimer\n`;
    mdContent += `This is a computer-generated report based on the data provided. Please consult a Chartered Accountant for final filing.\n`;

    zip.file("Reasoning_Report.md", mdContent);

    // Generate Zip
    const content = await zip.generateAsync({ type: "blob" });
    return content;
};
